### ISSUE TITLE
jobsite.co.uk 'Then I click the "edit cv" button': WebDriverError: unknown error: 'value' must be a string

### ISSUE THREAD

**Issue by DisasterMan78** [DisasterMan78/c-vpo#11]
```1) Scenario: Load site and login - features/jobsite.co.uk.feature:3
   Step: Then I click the "edit cv" button - features/jobsite.co.uk.feature:15
   Step Definition: features/stepdefinitions/generic.steps.js:98
   Message:
     WebDriverError: unknown error: 'value' must be a string
       (Session info: chrome=58.0.3029.110)
       (Driver info: chromedriver=2.28.455517 (2c6d2707d8ea850c862f04ac066724273981e88f),platform=Mac OS X 10.12.2 x86_64)
         at Object.checkLegacyResponse (/Users/davidbenson/Sites/c-vpo/node_modules/selenium-webdriver/lib/error.js:517:15)
         at parseHttpResponse (/Users/davidbenson/Sites/c-vpo/node_modules/selenium-webdriver/lib/http.js:516:11)
         at doSend.then.response (/Users/davidbenson/Sites/c-vpo/node_modules/selenium-webdriver/lib/http.js:432:13)
         at process._tickCallback (internal/process/next_tick.js:103:7)
     From: Task: WebDriver.findElement(By(css selector, undefined))
         at thenableWebDriverProxy.schedule (/Users/davidbenson/Sites/c-vpo/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
         at thenableWebDriverProxy.findElement (/Users/davidbenson/Sites/c-vpo/node_modules/selenium-webdriver/lib/webdriver.js:1023:17)
         at World.<anonymous> (/Users/davidbenson/Sites/c-vpo/features/stepdefinitions/generic.steps.js:132:35)
         at _combinedTickCallback (internal/process/next_tick.js:67:7)
         at process._tickCallback (internal/process/next_tick.js:98:9)
     From: Task: WebDriver.executeScript()
         at thenableWebDriverProxy.schedule (/Users/davidbenson/Sites/c-vpo/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
         at thenableWebDriverProxy.executeScript (/Users/davidbenson/Sites/c-vpo/node_modules/selenium-webdriver/lib/webdriver.js:887:16)
         at World.<anonymous> (/Users/davidbenson/Sites/c-vpo/features/stepdefinitions/generic.steps.js:137:28)
         at _combinedTickCallback (internal/process/next_tick.js:67:7)
         at process._tickCallback (internal/process/next_tick.js:98:9)```

**Comment by DisasterMan78** [comment]
Absolute plonker forgot a `break` in a `switch` case.
