### ISSUE TITLE
cwjobs.co.uk not working

### ISSUE THREAD

**Issue by rk295** [DisasterMan78/c-vpo#14]
Produces the following error:

```
> C-VPO@0.0.1 start /Users/robin/GIT/rk295/c-vpo
> cucumber-js "features/cwjobs.co.uk.feature"

Feature: cwjobs.co.uk CV upload

  Scenario: Load site and login
  ✔ Given I am using the data for "cwjobs.co.uk"
  ✔ And I visit the "login" page
  ✔ Then the page should have a login form
  ✖ And I should be able to enter my "username"
  - And I should be able to enter my "password"
  - And I should be able to submit the "login" form
  - Given I visit the "cv" page
  - Then I should be able to add my CV
  - And I should be able to submit the "cv" form

Failures:

1) Scenario: Load site and login - features/cwjobs.co.uk.feature:3
   Step: And I should be able to enter my "username" - features/cwjobs.co.uk.feature:7
   Step Definition: features/stepdefinitions/generic.steps.js:52
   Message:
     TypeError: Cannot read property 'username' of undefined
         at World.<anonymous> (/Users/robin/GIT/rk295/c-vpo/features/stepdefinitions/generic.steps.js:67:71)
         at processTicksAndRejections (internal/process/next_tick.js:74:9)

1 scenario (1 failed)
9 steps (1 failed, 5 skipped, 3 passed)
0m03.582s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! C-VPO@0.0.1 start: `cucumber-js "features/cwjobs.co.uk.feature"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the C-VPO@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robin/.npm/_logs/2019-03-29T13_08_07_588Z-debug.log
```

**Comment by rk295** [comment]
Looking at the form returned from the `loginUrl` it looks correct to me:

```
<form action="/Account/SignIn?ReturnUrl=%2FAuthenticated%2Fprofile.aspx" method="post" novalidate="novalidate">
    <div class="form-group">
        <label class="control-label" for="Form_Email">Email:</label> 
        <input class="form-control input-lg" data-val="true" data-val-required="Please provide an email address." id="Form_Email" name="Form.Email" type="email" value="" />
    </div>

    <div class="form-group">
        <label class="control-label" for="Form_Password">Password:</label>
        <input autocomplete="off" class="form-control input-lg" data-val="true" data-val-required="Please provide a password." id="Form_Password" name="Form.Password" type="password" value="" />
        <small class="pull-right forgotten-password">
            <a class="forgotten-password-link" href="/Account/ForgottenPassword?ReturnUrl=%2FAuthenticated%2Fprofile.aspx">
                Forgotten password?
            </a>
            </small>
    </div>

    <div class="form-group remember-me">
        <label>
            <input checked="checked" data-val="true" data-val-required="The RememberMe field is required." id="Form_RememberMe" name="Form.RememberMe" type="checkbox" value="true" />
            <input name="Form.RememberMe" type="hidden" value="false" />
            <label for="Form_RememberMe">Keep me signed in</label>
        </label>
    </div>

    <div class="form-group row">
        <div class="col-sm-9 col-md-6">
            <input type="submit" id="btnLogin" title="sign in" class="btn btn-exlg btn-primary btn-block" value="Sign in" />
        </div>
    </div>

    <div class="form-group"></div>
</form>
```

**Comment by DisasterMan78** [comment]
I'll try and take a quick look at these this weekend, but I'll be properly on the case with this by 11th April if you don't find fixes in the mean time.

Many thanks for posting the issues. Good lad! :p

**Comment by DisasterMan78** [comment]
Unable to replicate at this time.
