### ISSUE TITLE
jobserve.com is not working

### ISSUE THREAD

**Issue by rk295** [DisasterMan78/c-vpo#15]
Tried this morning, see this error:

```

> C-VPO@0.0.1 start /Users/robin/GIT/rk295/c-vpo
> cucumber-js "features/jobserve.com.feature"

Feature: jobserve.com CV upload

  Scenario: Load site and login
  ✔ Given I am using the data for "jobserve.com"
  ✔ And I visit the "login" page
  ✔ And I click the "allow cookies" button
  ✔ Then the page should have a login form
  ✔ And I should be able to enter my "username"
  ✔ And I should be able to enter my "password"
  ✔ And I should be able to submit the "login" form
  ✔ Then I wait for the "candidate home" page to load
  ✔ Then I click the "CVs tab" button
  ✔ And I wait for the "CV tab content" page to load
  ✔ And I hover on "actions element"
  ✔ And I click the "remove document" button
  ✖ Then I wait for the "confirm delete" page to load
  - And the page should say "are you sure"
  - Then I click the "confirm delete" button
  - And I wait for the "candidate home" page to load
  - Then I click the "CVs tab" button
  - And I wait for the "CV tab content" page to load
  - Then I click the "upload cv" button
  - Then I wait for the "upload cv" page to load
  - Then I should be able to add my CV
  - And I should be able to submit the "cv" form
  - Then I wait for the "candidate home" page to load

Failures:

1) Scenario: Load site and login - features/jobserve.com.feature:8
   Step: Then I wait for the "confirm delete" page to load - features/jobserve.com.feature:25
   Step Definition: features/stepdefinitions/generic.steps.js:145
   Message:
     TimeoutError: Waiting for element to be located By(css selector, #divConfirm #ConfirmButton)
     Wait timed out after 20000ms
         at /Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:2201:17
         at ManagedPromise.invokeCallback_ (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:1376:14)
         at TaskQueue.execute_ (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:3084:14)
         at TaskQueue.executeNext_ (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:3067:27)
         at asyncRun (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:2927:27)
         at /Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:668:7
         at processTicksAndRejections (internal/process/next_tick.js:81:5)
     From: Task: Waiting for element to be located By(css selector, #divConfirm #ConfirmButton)
         at scheduleWait (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:2188:20)
         at ControlFlow.wait (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:2517:12)
         at thenableWebDriverProxy.wait (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
         at World.waitFor (/Users/robin/GIT/rk295/c-vpo/features/support/world.js:65:19)
         at World.<anonymous> (/Users/robin/GIT/rk295/c-vpo/features/stepdefinitions/generic.steps.js:185:14)

1 scenario (1 failed)
23 steps (1 failed, 10 skipped, 12 passed)
0m27.460s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! C-VPO@0.0.1 start: `cucumber-js "features/jobserve.com.feature"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the C-VPO@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robin/.npm/_logs/2019-03-29T13_17_19_026Z-debug.log
```

I'll dig a bit more if time permits.

**Comment by DisasterMan78** [comment]
I don't have a jobserve account currently. I can create one to check it if this is still a problem, but you mentioned to me one was a config issue that you had resolved. Let me know and I'll  look into it if needs be.
