### ISSUE TITLE
totaljobs.com not working

### ISSUE THREAD

**Issue by rk295** [DisasterMan78/c-vpo#16]
Another one is failing:

```

> C-VPO@0.0.1 start /Users/robin/GIT/rk295/c-vpo
> cucumber-js "features/totaljobs.com.feature"

Feature: totaljobs.com CV upload

  Scenario: Load site and login
  ✔ Given I am using the data for "totaljobs.com"
  ✔ And I visit the "login" page
  ✔ Then the page should have a login form
  ✔ And I should be able to enter my "username"
  ✔ And I should be able to enter my "password"
  ✔ And I should be able to submit the "login" form
  ✔ Given I visit the "cv" page
  ✖ Then I should be able to add my CV
  - And I should be able to submit the "cv" form

Failures:

1) Scenario: Load site and login - features/totaljobs.com.feature:3
   Step: Then I should be able to add my CV - features/totaljobs.com.feature:13
   Step Definition: features/stepdefinitions/generic.steps.js:90
   Message:
     TimeoutError: Waiting for element to be located By(css selector, #candidateProfileDetails_cvUpload_filCVUploadFile)
     Wait timed out after 20001ms
         at /Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:2201:17
         at ManagedPromise.invokeCallback_ (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:1376:14)
         at TaskQueue.execute_ (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:3084:14)
         at TaskQueue.executeNext_ (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:3067:27)
         at asyncRun (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:2927:27)
         at /Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:668:7
         at processTicksAndRejections (internal/process/next_tick.js:81:5)
     From: Task: Waiting for element to be located By(css selector, #candidateProfileDetails_cvUpload_filCVUploadFile)
         at scheduleWait (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:2188:20)
         at ControlFlow.wait (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/promise.js:2517:12)
         at thenableWebDriverProxy.wait (/Users/robin/GIT/rk295/c-vpo/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
         at World.waitFor (/Users/robin/GIT/rk295/c-vpo/features/support/world.js:65:19)
         at World.<anonymous> (/Users/robin/GIT/rk295/c-vpo/features/stepdefinitions/generic.steps.js:92:14)

1 scenario (1 failed)
9 steps (1 failed, 1 skipped, 7 passed)
0m25.256s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! C-VPO@0.0.1 start: `cucumber-js "features/totaljobs.com.feature"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the C-VPO@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/robin/.npm/_logs/2019-03-29T13_19_09_814Z-debug.log
```

Again I'll dig if I get time! :)

**Comment by rk295** [comment]
mea culpa! Password for this one was wrong 🤦‍♂️. Others are fine from a password pov though. Closing.
